spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/concert?useSSL=false
    username: hhplus
    password: hhplus

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  sql:
    init:
      mode: always
      encoding: utf-8

  data:
    redis:
      port: 6379
      host: host.docker.internal
  cache:
    type: redis
  kafka:
    bootstrap-servers: host.docker.internal:9092

logging:
  level:
    org.hibernate.sql : DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder : TRACE