spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/concert
    username: hhplus
    password: hhplus

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  sql:
    init:
      mode: always
      encoding: utf-8

  data:
    redis:
      port: 6379
      host: localhost
  cache:
    type: redis

logging:
  level:
    org.hibernate.sql : DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder : TRACE