version: '3.8'

services:
  app:
    image: concert:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/concert
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=hhplus
    restart: on-failure
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=concert
      - MYSQL_ROOT_PASSWORD=hhplus
      - TZ='Asia/Seoul'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./mysql/init.d/init.sql:/docker-entrypoint-init.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 20s
      retries: 10

  redis:
    image: redis:latest
    volumes:
      - ./data:/data
    ports:
      - "6380:6379"
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  mysql-data: